POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName":"LokeshYadav" ,
    "username":"lokeshyadav",
    "email":"ly075097@gmail.com",
    "phone":"9996534089",
    "password":"mypassword"
}
