POST http://localhost:4001/customer/signup
Content-Type: application/json

{
    "firstname":"Lokesh" ,
    "lastname":"Yadav",
    "username":"lokeshyadav",
    "email":"ly075097@gmail.com",
    "phone":"9996534089",
    "password":"mypaasword"
}